Homework 9
DimitryusX/robotdreams pull request #5
Opened 2023-12-03 13:30 UTC by DimitryusX

2023-12-11 20:13 UTC, helen-black requested changes

2023-12-11 20:13 UTC, helen-black commented on Homework9/Utils.cpp
> +    }
functions shouldn't speak

2023-12-11 20:13 UTC, helen-black commented on Homework9/Utils.cpp
> +    }
don't print here, please. just update input str

2023-12-11 20:13 UTC, helen-black commented on Homework9/Utils.cpp
> +}
there is easuer way to solve this task

2023-12-11 20:13 UTC, helen-black commented on Homework9/Utils.cpp
> +bool isEqual(const char str1[], const char str2[])
test with 'abs' and 'absd'

2023-12-13 19:50 UTC, DimitryusX commented on Homework9/Utils.cpp
> +}
Fixed.

2023-12-13 19:50 UTC, DimitryusX commented on Homework9/Utils.cpp
> +bool isEqual(const char str1[], const char str2[])
Fixed.

2023-12-13 19:50 UTC, DimitryusX commented on Homework9/Utils.cpp
> +    }
Fixed.

2023-12-13 19:51 UTC, DimitryusX commented on Homework9/Utils.cpp
> +    }
Fixed.

2023-12-14 18:44 UTC, helen-black requested changes

2023-12-14 18:44 UTC, helen-black commented on Homework9/Utils.cpp
>          reversed += word[i];
it is the same algorithm

2023-12-14 18:44 UTC, helen-black commented on Homework9/Utils.cpp
> +
you don't use it

2023-12-14 21:46 UTC, DimitryusX commented on Homework9/Utils.cpp
> +
@helen-black yes, my mistake, forgot to remove debug.

2023-12-14 21:49 UTC, DimitryusX commented on Homework9/Utils.cpp
>          reversed += word[i];
@helen-black can't find a better solution. :(

2023-12-14 21:52 UTC, DimitryusX commented on Homework9/Utils.cpp
>          reversed += word[i];
@helen-black I can compare the original word with the reverted, don't understand how it is possible to add more optimization.

2023-12-14 21:52 UTC, merged